lista=["hola",7,3.5,True,9,"mundo",False,4.5]
print(lista)
print(lista[1])
print(lista[0:3])
print(lista[5:8])
print(lista[3:5])
lista.append("curso")
print(lista)
lista[3]=lista[7]
print(lista)
print(lista[0:9:3])
